### ISSUE TITLE
似乎测试用例的require的目录有一些问题

### ISSUE THREAD

**Issue by yipyeukyi** [cccdl/yunxin_sdk#3]
windows的php环境下提示找不到，后使用include该用绝对目录成功。

**Comment by cccdl** [comment]
能否告知下，什么文件？

**Comment by yipyeukyi** [comment]
composer拉取到vendor目录后从ip地址访问example目录下的测试文件报错，可能是访问方式不一样的问题吧。

Warning: require_once(/www/wwwroot/name.cc/vendor/cccdl/yunxin_sdk/src/examples/../../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/name.cc/vendor/cccdl/yunxin_sdk/src/examples/subsecribe_batchDel.php on line 3

**Comment by cccdl** [comment]
example目录针对的是本SDK包目录使用的示例文件，如果需要在站点composer引入此包后，不需要使用示例，直接使用类

**Comment by cccdl** [comment]
`<?php

use cccdl\yunxin_sdk\Im\User;

$im = new User($appKey, $appSecrt);

$res = $im->create('100001');`

**Comment by cccdl** [comment]
`<?php

use cccdl\yunxin_sdk\Im\User;

$im = new User($appKey, $appSecrt);

$res =  @$im->create('100001');`

**Comment by yipyeukyi** [comment]
\(^o^)/~，感谢指点。

**Comment by cccdl** [comment]
不用客气
